/**
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Address {
    ID?: string;
    DateCreated?: string;
    CompanyName?: string;
    FirstName?: string;
    LastName?: string;
    Street1?: string;
    Street2?: string;
    City?: string;
    State?: string;
    Zip?: string;
    Country?: string;
    Phone?: string;
    AddressName?: string;
    xp?: any;
}
