/**
 * OrderCloud
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * Contact: ordercloud@four51.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Meta } from './meta';
import { ProductAssignment } from './productAssignment';


export interface ListProductAssignment {
    Items?: Array<ProductAssignment>;
    Meta?: Meta;
}
