/**
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BuyerAddress } from './buyerAddress';
import { Meta } from './meta';


export interface ListBuyerAddress {
    Items?: Array<BuyerAddress>;
    Meta?: Meta;
}
