/**
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Meta } from './meta';
import { SpecProductAssignment } from './specProductAssignment';


export interface ListSpecProductAssignment {
    Items?: Array<SpecProductAssignment>;
    Meta?: Meta;
}
