/**
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CreditCard } from './creditCard';
import { Meta } from './meta';


export interface ListCreditCard<CreditCardXp = any> {
    Items?: Array<CreditCard<CreditCardXp>>;
    Meta?: Meta;
}
