/**
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface PartialPaymentTransaction {
    ID?: string;
    Type?: string;
    DateExecuted?: string;
    Amount?: number;
    Succeeded?: boolean;
    ResultCode?: string;
    ResultMessage?: string;
    xp?: any;
}
