/**
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LineItemProduct } from './lineItemProduct';
import { LineItemSpec } from './lineItemSpec';


export interface ShipmentItem {
    OrderID?: string;
    LineItemID?: string;
    QuantityShipped?: number;
    UnitPrice?: number;
    CostCenter?: string;
    DateNeeded?: string;
    Product?: LineItemProduct;
    Specs?: Array<LineItemSpec>;
    xp?: any;
}
