/**
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Spec {
    OptionCount?: number;
    ID?: string;
    ListOrder?: number;
    Name?: string;
    DefaultValue?: string;
    Required?: boolean;
    AllowOpenText?: boolean;
    DefaultOptionID?: string;
    DefinesVariant?: boolean;
    xp?: any;
}
