/**
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface SpendingAccount {
    ID?: string;
    Name?: string;
    Balance?: number;
    AllowAsPaymentMethod?: boolean;
    RedemptionCode?: string;
    StartDate?: string;
    EndDate?: string;
    xp?: any;
}
