/**
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CostCenter } from './costCenter';
import { Meta } from './meta';


export interface ListCostCenter<CostCenterXp = any> {
    Items?: Array<CostCenter<CostCenterXp>>;
    Meta?: Meta;
}
