/**
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ApiClientAssignment } from './apiClientAssignment';
import { Meta } from './meta';


export interface ListApiClientAssignment {
    Items?: Array<ApiClientAssignment>;
    Meta?: Meta;
}
