/**
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Meta } from './meta';
import { User } from './user';


export interface ListUser<UserXp = any> {
    Items?: Array<User<UserXp>>;
    Meta?: Meta;
}
