/**
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MetaWithFacets } from './metaWithFacets';
import { Product } from './product';


export interface ListProduct<ProductXp = any, ListFacetXp = any> {
    Items?: Array<Product<ProductXp>>;
    Meta?: MetaWithFacets<ListFacetXp>;
}
