/**
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Address } from './address';
import { Meta } from './meta';


export interface ListAddress<AddressXp = any> {
    Items?: Array<Address<AddressXp>>;
    Meta?: Meta;
}
