/**
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LineItem } from './lineItem';
import { Order } from './order';
import { OrderCalculateResponse } from './orderCalculateResponse';
import { ProposedShipmentRatesResponse } from './proposedShipmentRatesResponse';


export interface OrderCalculation<OrderXp = any, UserXp = any, AddressXp = any, LineItemXp = any, ProductXp = any, LineItemVariantXp = any, ProposedShipmentXp = any, ProposedShipmentOptionXp = any, OrderCalculateResponseXp = any> {
    Order?: Order<OrderXp, UserXp, AddressXp>;
    LineItems?: Array<LineItem<LineItemXp, ProductXp, LineItemVariantXp, AddressXp>>;
    ProposedShipmentRatesResponse?: ProposedShipmentRatesResponse<ProposedShipmentXp, ProposedShipmentOptionXp>;
    OrderCalculateResponse?: OrderCalculateResponse<OrderCalculateResponseXp>;
}
