/**
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface PartialPromotion<PromotionXp = any> {
    ID?: string;
    Code?: string;
    Name?: string;
    RedemptionLimit?: number;
    RedemptionLimitPerUser?: number;
    RedemptionCount?: number;
    Description?: string;
    FinePrint?: string;
    StartDate?: string;
    ExpirationDate?: string;
    EligibleExpression?: string;
    ValueExpression?: string;
    CanCombine?: boolean;
    AllowAllBuyers?: boolean;
    xp?: PromotionXp;
}
