/**
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ProposedShipmentItem } from './proposedShipmentItem';
import { ProposedShipmentOption } from './proposedShipmentOption';


export interface ProposedShipment<ProposedShipmentXp = any, ProposedShipmentOptionXp = any> {
    ID?: string;
    xp?: ProposedShipmentXp;
    SelectedProposedShipmentOptionID?: string;
    ProposedShipmentItems?: Array<ProposedShipmentItem>;
    ProposedShipmentOptions?: Array<ProposedShipmentOption<ProposedShipmentOptionXp>>;
}
