/**
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../utils/encoder';

import { Observable }                                        from 'rxjs';
import { OcTokenService }                                      from './token.service';

import { IntegrationEvent } from '../model/integrationEvent';
import { ListIntegrationEvent } from '../model/listIntegrationEvent';
import { OrderShipMethodSelection } from '../model/orderShipMethodSelection';
import { OrderWorksheet } from '../model/orderWorksheet';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../utils/variables';
import { Configuration }                                     from '../configuration';


@Injectable({
    providedIn: 'root'
})
export class OcIntegrationEventService {

    protected basePath = 'https://api.ordercloud.io/v1';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();
    private impersonating = false;

    constructor(protected httpClient: HttpClient, protected ocTokenService: OcTokenService, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }
    /**
     * @description enable impersonation by calling this prior to any of the other methods in this service
     * 
     */
    public As(): this {
        this.impersonating = true;
        return this;
    }
    /**
     * 
     * 
     * @param integrationEventID ID of the integration event.
     * @param options.observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param options.reportProgress flag to report request and response progress.
     */
    public Delete(integrationEventID: string, options?: { observe?: 'body', reportProgress?: boolean}): Observable<any>;
    public Delete(integrationEventID: string, options?: { observe?: 'response', reportProgress?: boolean}): Observable<HttpResponse<any>>;
    public Delete(integrationEventID: string, options?: { observe?: 'events', reportProgress?: boolean}): Observable<HttpEvent<any>>;
    public Delete(integrationEventID: string, options?: { observe?: any, reportProgress?: boolean}): Observable<any> {
        let opts = options || {};
        if (opts.observe === null || opts.observe === undefined) {
            opts.observe = 'body';
        }
        if (opts.reportProgress === null || opts.reportProgress === undefined) {
            opts.reportProgress = false;
        }
        if (integrationEventID === null || integrationEventID === undefined) {
            throw new Error('Required parameter integrationEventID was null or undefined when calling Delete.');
        }

        let headers = this.defaultHeaders;

        // authentication (oauth2) required
        let accessToken = this.impersonating ? this.ocTokenService.GetImpersonation() : this.ocTokenService.GetAccess();
        this.impersonating = false;
        headers = headers.set('Authorization', 'Bearer ' + accessToken);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json',
            'text/plain; charset=utf-8'
        ];

        return this.httpClient.delete<any>(`${this.basePath}/integrationEvents/${encodeURIComponent(String(integrationEventID))}`,
            {
                headers: headers,
                observe: opts.observe,
                reportProgress: opts.reportProgress
            }
        );
    }
    /**
     * 
     * 
     * @param direction Direction of the order, from the current user&#39;s perspective. Possible values: incoming, outgoing.
     * @param orderID ID of the order.
     * @param options.observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param options.reportProgress flag to report request and response progress.
     */
    public Calculate<OrderXp = any, UserXp = any, AddressXp = any, LineItemXp = any, ProductXp = any, LineItemVariantXp = any, ShipEstimateResponseXp = any, ShipEstimateXp = any, ShipMethodXp = any, OrderCalculateResponseXp = any, OrderSubmitResponseXp = any>(direction: string, orderID: string, options?: { observe?: 'body', reportProgress?: boolean}): Observable<OrderWorksheet<OrderXp, UserXp, AddressXp, LineItemXp, ProductXp, LineItemVariantXp, ShipEstimateResponseXp, ShipEstimateXp, ShipMethodXp, OrderCalculateResponseXp, OrderSubmitResponseXp>>;
    public Calculate<OrderXp = any, UserXp = any, AddressXp = any, LineItemXp = any, ProductXp = any, LineItemVariantXp = any, ShipEstimateResponseXp = any, ShipEstimateXp = any, ShipMethodXp = any, OrderCalculateResponseXp = any, OrderSubmitResponseXp = any>(direction: string, orderID: string, options?: { observe?: 'response', reportProgress?: boolean}): Observable<HttpResponse<OrderWorksheet>>;
    public Calculate<OrderXp = any, UserXp = any, AddressXp = any, LineItemXp = any, ProductXp = any, LineItemVariantXp = any, ShipEstimateResponseXp = any, ShipEstimateXp = any, ShipMethodXp = any, OrderCalculateResponseXp = any, OrderSubmitResponseXp = any>(direction: string, orderID: string, options?: { observe?: 'events', reportProgress?: boolean}): Observable<HttpEvent<OrderWorksheet>>;
    public Calculate(direction: string, orderID: string, options?: { observe?: any, reportProgress?: boolean}): Observable<any> {
        let opts = options || {};
        if (opts.observe === null || opts.observe === undefined) {
            opts.observe = 'body';
        }
        if (opts.reportProgress === null || opts.reportProgress === undefined) {
            opts.reportProgress = false;
        }
        if (direction === null || direction === undefined) {
            throw new Error('Required parameter direction was null or undefined when calling Calculate.');
        }
        if (orderID === null || orderID === undefined) {
            throw new Error('Required parameter orderID was null or undefined when calling Calculate.');
        }

        let headers = this.defaultHeaders;

        // authentication (oauth2) required
        let accessToken = this.impersonating ? this.ocTokenService.GetImpersonation() : this.ocTokenService.GetAccess();
        this.impersonating = false;
        headers = headers.set('Authorization', 'Bearer ' + accessToken);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json',
            'text/plain; charset=utf-8'
        ];

        return this.httpClient.post<OrderWorksheet>(`${this.basePath}/orders/${encodeURIComponent(String(direction))}/${encodeURIComponent(String(orderID))}/calculate`,
            null,
            {
                headers: headers,
                observe: opts.observe,
                reportProgress: opts.reportProgress
            }
        );
    }
    /**
     * 
     * 
     * @param integrationEvent 
     * @param options.observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param options.reportProgress flag to report request and response progress.
     */
    public Create(integrationEvent: IntegrationEvent, options?: { observe?: 'body', reportProgress?: boolean}): Observable<IntegrationEvent>;
    public Create(integrationEvent: IntegrationEvent, options?: { observe?: 'response', reportProgress?: boolean}): Observable<HttpResponse<IntegrationEvent>>;
    public Create(integrationEvent: IntegrationEvent, options?: { observe?: 'events', reportProgress?: boolean}): Observable<HttpEvent<IntegrationEvent>>;
    public Create(integrationEvent: IntegrationEvent, options?: { observe?: any, reportProgress?: boolean}): Observable<any> {
        let opts = options || {};
        if (opts.observe === null || opts.observe === undefined) {
            opts.observe = 'body';
        }
        if (opts.reportProgress === null || opts.reportProgress === undefined) {
            opts.reportProgress = false;
        }
        if (integrationEvent === null || integrationEvent === undefined) {
            throw new Error('Required parameter integrationEvent was null or undefined when calling Create.');
        }

        let headers = this.defaultHeaders;

        // authentication (oauth2) required
        let accessToken = this.impersonating ? this.ocTokenService.GetImpersonation() : this.ocTokenService.GetAccess();
        this.impersonating = false;
        headers = headers.set('Authorization', 'Bearer ' + accessToken);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json',
            'text/plain; charset=utf-8'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<IntegrationEvent>(`${this.basePath}/integrationEvents`,
            integrationEvent,
            {
                headers: headers,
                observe: opts.observe,
                reportProgress: opts.reportProgress
            }
        );
    }
    /**
     * 
     * 
     * @param direction Direction of the order, from the current user&#39;s perspective. Possible values: incoming, outgoing.
     * @param orderID ID of the order.
     * @param options.observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param options.reportProgress flag to report request and response progress.
     */
    public EstimateShipping<OrderXp = any, UserXp = any, AddressXp = any, LineItemXp = any, ProductXp = any, LineItemVariantXp = any, ShipEstimateResponseXp = any, ShipEstimateXp = any, ShipMethodXp = any, OrderCalculateResponseXp = any, OrderSubmitResponseXp = any>(direction: string, orderID: string, options?: { observe?: 'body', reportProgress?: boolean}): Observable<OrderWorksheet<OrderXp, UserXp, AddressXp, LineItemXp, ProductXp, LineItemVariantXp, ShipEstimateResponseXp, ShipEstimateXp, ShipMethodXp, OrderCalculateResponseXp, OrderSubmitResponseXp>>;
    public EstimateShipping<OrderXp = any, UserXp = any, AddressXp = any, LineItemXp = any, ProductXp = any, LineItemVariantXp = any, ShipEstimateResponseXp = any, ShipEstimateXp = any, ShipMethodXp = any, OrderCalculateResponseXp = any, OrderSubmitResponseXp = any>(direction: string, orderID: string, options?: { observe?: 'response', reportProgress?: boolean}): Observable<HttpResponse<OrderWorksheet>>;
    public EstimateShipping<OrderXp = any, UserXp = any, AddressXp = any, LineItemXp = any, ProductXp = any, LineItemVariantXp = any, ShipEstimateResponseXp = any, ShipEstimateXp = any, ShipMethodXp = any, OrderCalculateResponseXp = any, OrderSubmitResponseXp = any>(direction: string, orderID: string, options?: { observe?: 'events', reportProgress?: boolean}): Observable<HttpEvent<OrderWorksheet>>;
    public EstimateShipping(direction: string, orderID: string, options?: { observe?: any, reportProgress?: boolean}): Observable<any> {
        let opts = options || {};
        if (opts.observe === null || opts.observe === undefined) {
            opts.observe = 'body';
        }
        if (opts.reportProgress === null || opts.reportProgress === undefined) {
            opts.reportProgress = false;
        }
        if (direction === null || direction === undefined) {
            throw new Error('Required parameter direction was null or undefined when calling EstimateShipping.');
        }
        if (orderID === null || orderID === undefined) {
            throw new Error('Required parameter orderID was null or undefined when calling EstimateShipping.');
        }

        let headers = this.defaultHeaders;

        // authentication (oauth2) required
        let accessToken = this.impersonating ? this.ocTokenService.GetImpersonation() : this.ocTokenService.GetAccess();
        this.impersonating = false;
        headers = headers.set('Authorization', 'Bearer ' + accessToken);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json',
            'text/plain; charset=utf-8'
        ];

        return this.httpClient.post<OrderWorksheet>(`${this.basePath}/orders/${encodeURIComponent(String(direction))}/${encodeURIComponent(String(orderID))}/estimateshipping`,
            null,
            {
                headers: headers,
                observe: opts.observe,
                reportProgress: opts.reportProgress
            }
        );
    }
    /**
     * 
     * 
     * @param integrationEventID ID of the integration event.
     * @param options.observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param options.reportProgress flag to report request and response progress.
     */
    public Get(integrationEventID: string, options?: { observe?: 'body', reportProgress?: boolean}): Observable<IntegrationEvent>;
    public Get(integrationEventID: string, options?: { observe?: 'response', reportProgress?: boolean}): Observable<HttpResponse<IntegrationEvent>>;
    public Get(integrationEventID: string, options?: { observe?: 'events', reportProgress?: boolean}): Observable<HttpEvent<IntegrationEvent>>;
    public Get(integrationEventID: string, options?: { observe?: any, reportProgress?: boolean}): Observable<any> {
        let opts = options || {};
        if (opts.observe === null || opts.observe === undefined) {
            opts.observe = 'body';
        }
        if (opts.reportProgress === null || opts.reportProgress === undefined) {
            opts.reportProgress = false;
        }
        if (integrationEventID === null || integrationEventID === undefined) {
            throw new Error('Required parameter integrationEventID was null or undefined when calling Get.');
        }

        let headers = this.defaultHeaders;

        // authentication (oauth2) required
        let accessToken = this.impersonating ? this.ocTokenService.GetImpersonation() : this.ocTokenService.GetAccess();
        this.impersonating = false;
        headers = headers.set('Authorization', 'Bearer ' + accessToken);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json',
            'text/plain; charset=utf-8'
        ];

        return this.httpClient.get<IntegrationEvent>(`${this.basePath}/integrationEvents/${encodeURIComponent(String(integrationEventID))}`,
            {
                headers: headers,
                observe: opts.observe,
                reportProgress: opts.reportProgress
            }
        );
    }
    /**
     * 
     * 
     * @param direction Direction of the order, from the current user&#39;s perspective. Possible values: incoming, outgoing.
     * @param orderID ID of the order.
     * @param options.observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param options.reportProgress flag to report request and response progress.
     */
    public GetWorksheet<OrderXp = any, UserXp = any, AddressXp = any, LineItemXp = any, ProductXp = any, LineItemVariantXp = any, ShipEstimateResponseXp = any, ShipEstimateXp = any, ShipMethodXp = any, OrderCalculateResponseXp = any, OrderSubmitResponseXp = any>(direction: string, orderID: string, options?: { observe?: 'body', reportProgress?: boolean}): Observable<OrderWorksheet<OrderXp, UserXp, AddressXp, LineItemXp, ProductXp, LineItemVariantXp, ShipEstimateResponseXp, ShipEstimateXp, ShipMethodXp, OrderCalculateResponseXp, OrderSubmitResponseXp>>;
    public GetWorksheet<OrderXp = any, UserXp = any, AddressXp = any, LineItemXp = any, ProductXp = any, LineItemVariantXp = any, ShipEstimateResponseXp = any, ShipEstimateXp = any, ShipMethodXp = any, OrderCalculateResponseXp = any, OrderSubmitResponseXp = any>(direction: string, orderID: string, options?: { observe?: 'response', reportProgress?: boolean}): Observable<HttpResponse<OrderWorksheet>>;
    public GetWorksheet<OrderXp = any, UserXp = any, AddressXp = any, LineItemXp = any, ProductXp = any, LineItemVariantXp = any, ShipEstimateResponseXp = any, ShipEstimateXp = any, ShipMethodXp = any, OrderCalculateResponseXp = any, OrderSubmitResponseXp = any>(direction: string, orderID: string, options?: { observe?: 'events', reportProgress?: boolean}): Observable<HttpEvent<OrderWorksheet>>;
    public GetWorksheet(direction: string, orderID: string, options?: { observe?: any, reportProgress?: boolean}): Observable<any> {
        let opts = options || {};
        if (opts.observe === null || opts.observe === undefined) {
            opts.observe = 'body';
        }
        if (opts.reportProgress === null || opts.reportProgress === undefined) {
            opts.reportProgress = false;
        }
        if (direction === null || direction === undefined) {
            throw new Error('Required parameter direction was null or undefined when calling GetWorksheet.');
        }
        if (orderID === null || orderID === undefined) {
            throw new Error('Required parameter orderID was null or undefined when calling GetWorksheet.');
        }

        let headers = this.defaultHeaders;

        // authentication (oauth2) required
        let accessToken = this.impersonating ? this.ocTokenService.GetImpersonation() : this.ocTokenService.GetAccess();
        this.impersonating = false;
        headers = headers.set('Authorization', 'Bearer ' + accessToken);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json',
            'text/plain; charset=utf-8'
        ];

        return this.httpClient.get<OrderWorksheet>(`${this.basePath}/orders/${encodeURIComponent(String(direction))}/${encodeURIComponent(String(orderID))}/worksheet`,
            {
                headers: headers,
                observe: opts.observe,
                reportProgress: opts.reportProgress
            }
        );
    }
    /**
     * 
     * 
     * @param options.search Word or phrase to search for.
     * @param options.searchOn Comma-delimited list of fields to search on.
     * @param options.sortBy Comma-delimited list of fields to sort by.
     * @param options.page Page of results to return. Default: 1
     * @param options.pageSize Number of results to return per page. Default: 20, max: 100.
     * @param options.filters Any additional key/value pairs passed in the query string are interpretted as filters. Valid keys are top-level properties of the returned model or &#39;xp.???&#39;
     * @param options.observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param options.reportProgress flag to report request and response progress.
     */
   
    public List(options?: { search?: string, searchOn?: string, sortBy?: string, page?: number, pageSize?: number, filters?: { [key: string]: string | Array<string>; }, observe?: 'body', reportProgress?: boolean}): Observable<ListIntegrationEvent>;
    public List(options?: { search?: string, searchOn?: string, sortBy?: string, page?: number, pageSize?: number, filters?: { [key: string]: string | Array<string>; }, observe?: 'response', reportProgress?: boolean}): Observable<HttpResponse<ListIntegrationEvent>>;
    public List(options?: { search?: string, searchOn?: string, sortBy?: string, page?: number, pageSize?: number, filters?: { [key: string]: string | Array<string>; }, observe?: 'events', reportProgress?: boolean}): Observable<HttpEvent<ListIntegrationEvent>>;
    public List(options?: { search?: string, searchOn?: string, sortBy?: string, page?: number, pageSize?: number, filters?: { [key: string]: string | Array<string>; }, observe?: any, reportProgress?: boolean}): Observable<any> {
        let opts = options || {};
        if (opts.observe === null || opts.observe === undefined) {
            opts.observe = 'body';
        }
        if (opts.reportProgress === null || opts.reportProgress === undefined) {
            opts.reportProgress = false;
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (opts.search !== undefined) {
            queryParameters = queryParameters.set('search', <any>opts.search);
        }
        if (opts.search === null) {
            throw new Error('Parameter search was null when calling List. Null values are not allowed');
        }
        if (opts.searchOn !== undefined) {
            queryParameters = queryParameters.set('searchOn', <any>opts.searchOn);
        }
        if (opts.searchOn === null) {
            throw new Error('Parameter searchOn was null when calling List. Null values are not allowed');
        }
        if (opts.sortBy !== undefined) {
            queryParameters = queryParameters.set('sortBy', <any>opts.sortBy);
        }
        if (opts.sortBy === null) {
            throw new Error('Parameter sortBy was null when calling List. Null values are not allowed');
        }
        if (opts.page !== undefined) {
            queryParameters = queryParameters.set('page', <any>opts.page);
        }
        if (opts.page === null) {
            throw new Error('Parameter page was null when calling List. Null values are not allowed');
        }
        if (opts.pageSize !== undefined) {
            queryParameters = queryParameters.set('pageSize', <any>opts.pageSize);
        }
        if (opts.pageSize === null) {
            throw new Error('Parameter pageSize was null when calling List. Null values are not allowed');
        }
        if (opts.filters !== undefined) {
            queryParameters = this.configuration.unwrapFilters(opts.filters, queryParameters, 'List');
        }
        if (opts.filters === null) {
            throw new Error('Parameter filters was null when calling List. Null values are not allowed');
        }

        let headers = this.defaultHeaders;

        // authentication (oauth2) required
        let accessToken = this.impersonating ? this.ocTokenService.GetImpersonation() : this.ocTokenService.GetAccess();
        this.impersonating = false;
        headers = headers.set('Authorization', 'Bearer ' + accessToken);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json',
            'text/plain; charset=utf-8'
        ];

        return this.httpClient.get<ListIntegrationEvent>(`${this.basePath}/integrationEvents`,
            {
                params: queryParameters,
                headers: headers,
                observe: opts.observe,
                reportProgress: opts.reportProgress
            }
        );
    }
    /**
     * 
     * 
     * @param integrationEventID ID of the integration event.
     * @param partialIntegrationEvent 
     * @param options.observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param options.reportProgress flag to report request and response progress.
     */
    public Patch(integrationEventID: string, partialIntegrationEvent: IntegrationEvent, options?: { observe?: 'body', reportProgress?: boolean}): Observable<IntegrationEvent>;
    public Patch(integrationEventID: string, partialIntegrationEvent: IntegrationEvent, options?: { observe?: 'response', reportProgress?: boolean}): Observable<HttpResponse<IntegrationEvent>>;
    public Patch(integrationEventID: string, partialIntegrationEvent: IntegrationEvent, options?: { observe?: 'events', reportProgress?: boolean}): Observable<HttpEvent<IntegrationEvent>>;
    public Patch(integrationEventID: string, partialIntegrationEvent: IntegrationEvent, options?: { observe?: any, reportProgress?: boolean}): Observable<any> {
        let opts = options || {};
        if (opts.observe === null || opts.observe === undefined) {
            opts.observe = 'body';
        }
        if (opts.reportProgress === null || opts.reportProgress === undefined) {
            opts.reportProgress = false;
        }
        if (integrationEventID === null || integrationEventID === undefined) {
            throw new Error('Required parameter integrationEventID was null or undefined when calling Patch.');
        }
        if (partialIntegrationEvent === null || partialIntegrationEvent === undefined) {
            throw new Error('Required parameter partialIntegrationEvent was null or undefined when calling Patch.');
        }

        let headers = this.defaultHeaders;

        // authentication (oauth2) required
        let accessToken = this.impersonating ? this.ocTokenService.GetImpersonation() : this.ocTokenService.GetAccess();
        this.impersonating = false;
        headers = headers.set('Authorization', 'Bearer ' + accessToken);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json',
            'text/plain; charset=utf-8'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.patch<IntegrationEvent>(`${this.basePath}/integrationEvents/${encodeURIComponent(String(integrationEventID))}`,
            partialIntegrationEvent,
            {
                headers: headers,
                observe: opts.observe,
                reportProgress: opts.reportProgress
            }
        );
    }
    /**
     * 
     * 
     * @param integrationEventID ID of the integration event.
     * @param integrationEvent 
     * @param options.observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param options.reportProgress flag to report request and response progress.
     */
    public Save(integrationEventID: string, integrationEvent: IntegrationEvent, options?: { observe?: 'body', reportProgress?: boolean}): Observable<IntegrationEvent>;
    public Save(integrationEventID: string, integrationEvent: IntegrationEvent, options?: { observe?: 'response', reportProgress?: boolean}): Observable<HttpResponse<IntegrationEvent>>;
    public Save(integrationEventID: string, integrationEvent: IntegrationEvent, options?: { observe?: 'events', reportProgress?: boolean}): Observable<HttpEvent<IntegrationEvent>>;
    public Save(integrationEventID: string, integrationEvent: IntegrationEvent, options?: { observe?: any, reportProgress?: boolean}): Observable<any> {
        let opts = options || {};
        if (opts.observe === null || opts.observe === undefined) {
            opts.observe = 'body';
        }
        if (opts.reportProgress === null || opts.reportProgress === undefined) {
            opts.reportProgress = false;
        }
        if (integrationEventID === null || integrationEventID === undefined) {
            throw new Error('Required parameter integrationEventID was null or undefined when calling Save.');
        }
        if (integrationEvent === null || integrationEvent === undefined) {
            throw new Error('Required parameter integrationEvent was null or undefined when calling Save.');
        }

        let headers = this.defaultHeaders;

        // authentication (oauth2) required
        let accessToken = this.impersonating ? this.ocTokenService.GetImpersonation() : this.ocTokenService.GetAccess();
        this.impersonating = false;
        headers = headers.set('Authorization', 'Bearer ' + accessToken);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json',
            'text/plain; charset=utf-8'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.put<IntegrationEvent>(`${this.basePath}/integrationEvents/${encodeURIComponent(String(integrationEventID))}`,
            integrationEvent,
            {
                headers: headers,
                observe: opts.observe,
                reportProgress: opts.reportProgress
            }
        );
    }
    /**
     * 
     * 
     * @param direction Direction of the order, from the current user&#39;s perspective. Possible values: incoming, outgoing.
     * @param orderID ID of the order.
     * @param orderShipMethodSelection 
     * @param options.observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param options.reportProgress flag to report request and response progress.
     */
    public SelectShipmethods<OrderXp = any, UserXp = any, AddressXp = any, LineItemXp = any, ProductXp = any, LineItemVariantXp = any, ShipEstimateResponseXp = any, ShipEstimateXp = any, ShipMethodXp = any, OrderCalculateResponseXp = any, OrderSubmitResponseXp = any>(direction: string, orderID: string, orderShipMethodSelection: OrderShipMethodSelection, options?: { observe?: 'body', reportProgress?: boolean}): Observable<OrderWorksheet<OrderXp, UserXp, AddressXp, LineItemXp, ProductXp, LineItemVariantXp, ShipEstimateResponseXp, ShipEstimateXp, ShipMethodXp, OrderCalculateResponseXp, OrderSubmitResponseXp>>;
    public SelectShipmethods<OrderXp = any, UserXp = any, AddressXp = any, LineItemXp = any, ProductXp = any, LineItemVariantXp = any, ShipEstimateResponseXp = any, ShipEstimateXp = any, ShipMethodXp = any, OrderCalculateResponseXp = any, OrderSubmitResponseXp = any>(direction: string, orderID: string, orderShipMethodSelection: OrderShipMethodSelection, options?: { observe?: 'response', reportProgress?: boolean}): Observable<HttpResponse<OrderWorksheet>>;
    public SelectShipmethods<OrderXp = any, UserXp = any, AddressXp = any, LineItemXp = any, ProductXp = any, LineItemVariantXp = any, ShipEstimateResponseXp = any, ShipEstimateXp = any, ShipMethodXp = any, OrderCalculateResponseXp = any, OrderSubmitResponseXp = any>(direction: string, orderID: string, orderShipMethodSelection: OrderShipMethodSelection, options?: { observe?: 'events', reportProgress?: boolean}): Observable<HttpEvent<OrderWorksheet>>;
    public SelectShipmethods(direction: string, orderID: string, orderShipMethodSelection: OrderShipMethodSelection, options?: { observe?: any, reportProgress?: boolean}): Observable<any> {
        let opts = options || {};
        if (opts.observe === null || opts.observe === undefined) {
            opts.observe = 'body';
        }
        if (opts.reportProgress === null || opts.reportProgress === undefined) {
            opts.reportProgress = false;
        }
        if (direction === null || direction === undefined) {
            throw new Error('Required parameter direction was null or undefined when calling SelectShipmethods.');
        }
        if (orderID === null || orderID === undefined) {
            throw new Error('Required parameter orderID was null or undefined when calling SelectShipmethods.');
        }
        if (orderShipMethodSelection === null || orderShipMethodSelection === undefined) {
            throw new Error('Required parameter orderShipMethodSelection was null or undefined when calling SelectShipmethods.');
        }

        let headers = this.defaultHeaders;

        // authentication (oauth2) required
        let accessToken = this.impersonating ? this.ocTokenService.GetImpersonation() : this.ocTokenService.GetAccess();
        this.impersonating = false;
        headers = headers.set('Authorization', 'Bearer ' + accessToken);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json',
            'text/plain; charset=utf-8'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<OrderWorksheet>(`${this.basePath}/orders/${encodeURIComponent(String(direction))}/${encodeURIComponent(String(orderID))}/shipmethods`,
            orderShipMethodSelection,
            {
                headers: headers,
                observe: opts.observe,
                reportProgress: opts.reportProgress
            }
        );
    }
 }
