export * from './address.service';
import { OcAddressService } from './address.service';
export * from './adminAddress.service';
import { OcAdminAddressService } from './adminAddress.service';
export * from './adminUser.service';
import { OcAdminUserService } from './adminUser.service';
export * from './adminUserGroup.service';
import { OcAdminUserGroupService } from './adminUserGroup.service';
export * from './approvalRule.service';
import { OcApprovalRuleService } from './approvalRule.service';
export * from './buyer.service';
import { OcBuyerService } from './buyer.service';
export * from './catalog.service';
import { OcCatalogService } from './catalog.service';
export * from './category.service';
import { OcCategoryService } from './category.service';
export * from './costCenter.service';
import { OcCostCenterService } from './costCenter.service';
export * from './creditCard.service';
import { OcCreditCardService } from './creditCard.service';
export * from './impersonationConfig.service';
import { OcImpersonationConfigService } from './impersonationConfig.service';
export * from './incrementor.service';
import { OcIncrementorService } from './incrementor.service';
export * from './lineItem.service';
import { OcLineItemService } from './lineItem.service';
export * from './me.service';
import { OcMeService } from './me.service';
export * from './messageSender.service';
import { OcMessageSenderService } from './messageSender.service';
export * from './order.service';
import { OcOrderService } from './order.service';
export * from './passwordReset.service';
import { OcPasswordResetService } from './passwordReset.service';
export * from './payment.service';
import { OcPaymentService } from './payment.service';
export * from './priceSchedule.service';
import { OcPriceScheduleService } from './priceSchedule.service';
export * from './product.service';
import { OcProductService } from './product.service';
export * from './promotion.service';
import { OcPromotionService } from './promotion.service';
export * from './securityProfile.service';
import { OcSecurityProfileService } from './securityProfile.service';
export * from './shipment.service';
import { OcShipmentService } from './shipment.service';
export * from './spec.service';
import { OcSpecService } from './spec.service';
export * from './spendingAccount.service';
import { OcSpendingAccountService } from './spendingAccount.service';
export * from './supplier.service';
import { OcSupplierService } from './supplier.service';
export * from './supplierAddress.service';
import { OcSupplierAddressService } from './supplierAddress.service';
export * from './supplierUser.service';
import { OcSupplierUserService } from './supplierUser.service';
export * from './supplierUserGroup.service';
import { OcSupplierUserGroupService } from './supplierUserGroup.service';
export * from './user.service';
import { OcUserService } from './user.service';
export * from './userGroup.service';
import { OcUserGroupService } from './userGroup.service';
export * from './auth.service';
import { OcAuthService } from './auth.service';
export * from './token.service';
import { OcTokenService } from './token.service';
export const APIS = [OcAddressService, OcAdminAddressService, OcAdminUserService, OcAdminUserGroupService, OcApprovalRuleService, OcBuyerService, OcCatalogService, OcCategoryService, OcCostCenterService, OcCreditCardService, OcImpersonationConfigService, OcIncrementorService, OcLineItemService, OcMeService, OcMessageSenderService, OcOrderService, OcPasswordResetService, OcPaymentService, OcPriceScheduleService, OcProductService, OcPromotionService, OcSecurityProfileService, OcShipmentService, OcSpecService, OcSpendingAccountService, OcSupplierService, OcSupplierAddressService, OcSupplierUserService, OcSupplierUserGroupService, OcUserService, OcUserGroupService, OcAuthService, OcTokenService];
