export * from './address.service';
import { AddressService } from './address.service';
export * from './adminAddress.service';
import { AdminAddressService } from './adminAddress.service';
export * from './adminUser.service';
import { AdminUserService } from './adminUser.service';
export * from './adminUserGroup.service';
import { AdminUserGroupService } from './adminUserGroup.service';
export * from './approvalRule.service';
import { ApprovalRuleService } from './approvalRule.service';
export * from './buyer.service';
import { BuyerService } from './buyer.service';
export * from './catalog.service';
import { CatalogService } from './catalog.service';
export * from './category.service';
import { CategoryService } from './category.service';
export * from './costCenter.service';
import { CostCenterService } from './costCenter.service';
export * from './creditCard.service';
import { CreditCardService } from './creditCard.service';
export * from './impersonationConfig.service';
import { ImpersonationConfigService } from './impersonationConfig.service';
export * from './lineItem.service';
import { LineItemService } from './lineItem.service';
export * from './me.service';
import { MeService } from './me.service';
export * from './messageSenders.service';
import { MessageSendersService } from './messageSenders.service';
export * from './order.service';
import { OrderService } from './order.service';
export * from './passwordReset.service';
import { PasswordResetService } from './passwordReset.service';
export * from './payment.service';
import { PaymentService } from './payment.service';
export * from './priceSchedule.service';
import { PriceScheduleService } from './priceSchedule.service';
export * from './product.service';
import { ProductService } from './product.service';
export * from './promotion.service';
import { PromotionService } from './promotion.service';
export * from './securityProfile.service';
import { SecurityProfileService } from './securityProfile.service';
export * from './shipment.service';
import { ShipmentService } from './shipment.service';
export * from './spec.service';
import { SpecService } from './spec.service';
export * from './spendingAccount.service';
import { SpendingAccountService } from './spendingAccount.service';
export * from './supplier.service';
import { SupplierService } from './supplier.service';
export * from './supplierUser.service';
import { SupplierUserService } from './supplierUser.service';
export * from './supplierUserGroup.service';
import { SupplierUserGroupService } from './supplierUserGroup.service';
export * from './user.service';
import { UserService } from './user.service';
export * from './userGroup.service';
import { UserGroupService } from './userGroup.service';
export * from './auth.service';
import { AuthService } from './auth.service';
export * from './token.service';
import { TokenService } from './token.service';
export const APIS = [AddressService, AdminAddressService, AdminUserService, AdminUserGroupService, ApprovalRuleService, BuyerService, CatalogService, CategoryService, CostCenterService, CreditCardService, ImpersonationConfigService, LineItemService, MeService, MessageSendersService, OrderService, PasswordResetService, PaymentService, PriceScheduleService, ProductService, PromotionService, SecurityProfileService, ShipmentService, SpecService, SpendingAccountService, SupplierService, SupplierUserService, SupplierUserGroupService, UserService, UserGroupService, AuthService, TokenService];
